// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlhygDJqlq9H-pdhrK_3zKPovJ5TqJfVc',
    appId: '1:523334438989:web:31d2da2b28e74c529a8c04',
    messagingSenderId: '523334438989',
    projectId: 'bookswap-application',
    authDomain: 'bookswap-application.firebaseapp.com',
    storageBucket: 'bookswap-application.firebasestorage.app',
    measurementId: 'G-L7JJF5XRR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk9R9Q4y2M3TXrOSTzETid_uI5vaSV-t0',
    appId: '1:523334438989:android:372f8105445557bd9a8c04',
    messagingSenderId: '523334438989',
    projectId: 'bookswap-application',
    storageBucket: 'bookswap-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6To0hrrF05jGOVQ5Rs8x3VKLB-WtYFP4',
    appId: '1:523334438989:ios:4f65da152413296f9a8c04',
    messagingSenderId: '523334438989',
    projectId: 'bookswap-application',
    storageBucket: 'bookswap-application.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6To0hrrF05jGOVQ5Rs8x3VKLB-WtYFP4',
    appId: '1:523334438989:ios:4f65da152413296f9a8c04',
    messagingSenderId: '523334438989',
    projectId: 'bookswap-application',
    storageBucket: 'bookswap-application.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlhygDJqlq9H-pdhrK_3zKPovJ5TqJfVc',
    appId: '1:523334438989:web:b4677b6375ce2f9e9a8c04',
    messagingSenderId: '523334438989',
    projectId: 'bookswap-application',
    authDomain: 'bookswap-application.firebaseapp.com',
    storageBucket: 'bookswap-application.firebasestorage.app',
    measurementId: 'G-X7MNMK0K1N',
  );

}